In [1]:
import numpy as np
import matplotlib as plt
import math

In [2]:
mat=np.array([[1,-1,1],[0,0,1],[-1,0,0]])
rank=np.sum(np.absolute(mat))
print(rank)

5


In [3]:
Line=np.ones((1,(mat).shape[0]))
Line2=np.ones(((mat).shape[0],1))
print(Line,Line2)

[[1. 1. 1.]] [[1.]
 [1.]
 [1.]]


In [4]:
print(np.ones((1,3)))

[[1. 1. 1.]]


In [5]:
deapth=4
def CreatDimCheat(U0):
    DimCheat=[]
    for i in range(deapth+1):
        DimCheat.append(U0)
        U0=U0*3+2*(i+1)
    return DimCheat
print(CreatDimCheat(3))

[3, 11, 37, 117, 359]


In [19]:
A=np.array([[1,0,1],[0,0,1],[1,0,0]])
A=np.concatenate([np.atleast_3d(A),np.atleast_3d(A),np.atleast_3d(A)],axis=2)
A

array([[[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]],

       [[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]]])

In [20]:
A[:,:,:3][(A[:,:,1]==0)]=[3,5,6]
A

array([[[1, 1, 1],
        [3, 5, 6],
        [1, 1, 1]],

       [[3, 5, 6],
        [3, 5, 6],
        [1, 1, 1]],

       [[1, 1, 1],
        [3, 5, 6],
        [3, 5, 6]]])

In [4]:
A=np.array([455,45,69])
A[A>255]=255
A

array([255,  45,  69])

In [7]:
print('C:\\Users\\adhem\\Documents\\Algo\\Marth\\MathPython\\name.png')

C:\Users\adhem\Documents\Algo\Marth\MathPython\name.png
